
CREATE SEQUENCE SEQ_PRODUCT;

CREATE TABLE JUNGMIN_PRODUCT(
	PRODUCT_ID NUMBER CONSTRAINT PK_PRODUCT PRIMARY KEY, -- 상품 ID
	PRODUCT_NAME VARCHAR2(500) NOT NULL, -- 상품 이름
	PRODUCT_STOCK NUMBER DEFAULT 0, -- 상품 재고
	PRODUCT_PRICE NUMBER DEFAULT 0, -- 상품 가격
	REGISTER_DATE DATE DEFAULT SYSDATE,
	UPDATE_DATE DATE DEFAULT SYSDATE
);

DROP TABLE JUNGMIN_PRODUCT;

ALTER TABLE JUNGMIN_PRODUCT ADD (REGISTER_DATE DATE);
ALTER TABLE JUNGMIN_PRODUCT ADD (UPDATE_DATE DATE);

ALTER TABLE JUNGMIN_PRODUCT MODIFY(REGISTER_DATE DEFAULT SYSDATE);
ALTER TABLE JUNGMIN_PRODUCT MODIFY(UPDATE_DATE DEFAULT SYSDATE);

SELECT * FROM JUNGMIN_PRODUCT ORDER BY PRODUCT_ID DESC;




